config/routes.rb
Rails.application.routes.draw do
  root 'taxonomy_prints#new'
  # post "/taxonomy_prints" => 'taxonomy_prints#create'
  resources :taxonomy_prints, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/taxonomy_prints_controller.rb
class TaxonomyPrintsController < ActionController::Base
  require 'csv'
  before_action :build_tree

  def new; end

  def show
    av= ActionView::Base.new(Rails.root.join('app/views'))

    filename = "Try_not_to_be_an_asshole"
    filename = filename.gsub(/[^\w\.]/, '_')
    filename += ".pdf"


    pdf = render_to_string(pdf: filename,
                            template: 'taxonomy_prints/show.pdf.erb',
                            page_size: "Letter",
                            dpi: '300',
                            encoding: 'utf8',
                            javascript_delay: 5000,
                            page_height: @height_mm,
                            page_width: @width_mm,
                            )
    send_data(pdf, filename: filename, type: "application/pdf")
  end
private
  def build_tree
    tree_csv = CSV.read("tree.csv")
    homogeneity_scores = CSV.read("taxon_homogeneity.csv")
    @tree_presenter = TaxonomyPresenter.new(tree_csv, homogeneity_scores)
    @tree = @tree_presenter.present.to_json
    @height = @tree_presenter.height
    @width = @tree_presenter.width
    @width_mm = @width * 0.2645833333
    @height_mm = @height * 0.2645833333
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrintTheWholeDamnTaxonomy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>
    <%= yield %>
  </body>
</html>

app/views/taxonomy_prints/new.html.erb
<h1>The whole damn taxonomy</h1>
<h3>Explanation</h3>
<p>This shows the tree structure with metrics, colour coded to easily show more, or less, "healthy" taxons, key for each entry as follows</p>
<p>Taxon name (eg Entering and staying in the UK)</p>
<p>"# tagged to it" The number of content items tagged directly to that taxon (eg 283)</p>
<p>"# tagged to it + chldrn" The number of content items tagged to it and all its descendants (eg 4947)</p>
<p>"coarseness" The total number of content items tagged to it and all its descendants, divided by the total depth of all it's descendants (where, for example, 2 level 5 taxons 'score' 10) (eg 0)</p>
<p>"coarseness score" A score from 0 to 2 (lower is better) against all other taxons on the same level, a score of 2 says its in the worst third (ie highest coarseness scores), 1 in the middle third and 0 says it's in the bottom third (ie lowest coarseness scores)</p>
<p>"percentage tagged to level" the percentage of content tagged to that taxon compared to it's siblings (eg 0)</p>
<p>"percentage difference to level" the difference between the percentage tagged to that level compared to what we'd expect (so if a taxon has 3 siblings, we'd expect 25% to be tagged to each, if a taxon has only 10% this would be 15%. It's an absolute score so 10% or 40% it would be 15% either way)</p>
<p>"percentage tagged to level score"A score from 0 to 2 (lower is better) against all other taxons on the same level, a score of 2 says its in the worst third (ie highest percentage difference), 1 in the middle third and 0 says it's in the bottom third (ie lowest percentage differences)</p>

<h3>Colouring</h3>
<p>Each taxon is colour coded, as you might expect, red is the worst, black is neutral and green is good (although these are relative scores so green might still be less than ideal)</p>
<p>There are two colours, the top half is for the coarseness score and the bottom half for the percentage score). This is because sometimes the coarseness score is a better measure but I wanted to keep the percentage score around to see how useful it is. If in doubt, probably best to ignore the percentage score and colour</p>


<%= link_to raw("<button type='submit' class='no-print'>Download PDF</button>"), taxonomy_print_path(id: 0), { remote: true, method: :get } %>
<p class="no-print"><%= @height_mm %> mm high</p>
<p class="no-print"><%= @width_mm %> mm wide</p>
<%= render "show" %>


<style>
  @media print
  {
    .no-print, .no-print *
    {
      display: none !important;
    }
  }
</style>

app/views/taxonomy_prints/show.pdf.erb
<!doctype html>
<html>
<head>
  <meta charset='utf-8' />
</head>
<body>
  <%= render(partial: "taxonomy_prints/show.html.erb") %>

</body>
</html>